--QUESTION 4A
WITH
LGA_REVENUE AS (
SELECT
	G.LGA_CODE,
	    D.LISTING_NEIGHBOURHOOD,
	    ROUND((SUM(D.AVG_ESTIMATED_REVENUE_PER_ACTIVE_LISTING)/ COUNT(D.*)), 2) AS REVENUE_PER_ACTIVE_LISTING
FROM
	GOLD.DM_LISTING_NEIGHBOURHOOD D
JOIN GOLD.G_DIM_LGA_SUBURB G
    ON
	D.LISTING_NEIGHBOURHOOD = G.LGA_NAME
GROUP BY
	G.LGA_CODE,
	D.LISTING_NEIGHBOURHOOD 
),

RANKED_LGAS AS (
    SELECT
		*,
        RANK() OVER (ORDER BY REVENUE_PER_ACTIVE_LISTING DESC) AS RANK_DESC,
        RANK() OVER (ORDER BY REVENUE_PER_ACTIVE_LISTING ASC)  AS RANK_ASC
    FROM LGA_REVENUE
),

SELECTED_LGAS AS (
    SELECT *, 
    CASE 
        WHEN RANK_DESC <= 3 THEN 'TOP 3'
        WHEN RANK_ASC <= 3 THEN 'BOTTOM 3'
    END AS REVENUE_RANK
    FROM RANKED_LGAS
    WHERE RANK_DESC <= 3 OR RANK_ASC <= 3
),

LGA_DEMOGRAPHICS AS (
    SELECT 
        SL.REVENUE_RANK,
        SL.LISTING_NEIGHBOURHOOD,
        REVENUE_PER_ACTIVE_LISTING,
        
        -- POPULATION, AGE ANG GENDER DEMOGRAPHICS
        C.TOTAL_PERSONS_TOTAL AS TOTAL_POPULATION,
        C.MEDIAN_AGE_PERSONS,
        ROUND((C.TOTAL_PERSONS_FEMALE::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_FEMALE,
        ROUND((C.TOTAL_PERSONS_MALE::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_MALE,

        
        -- AGE GROUP DISTRIBUTIONS (AS PERCENTAGES)
        ROUND((C.POPULATION_0_4_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_0_4,
        ROUND((C.POPULATION_5_14_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_5_14,
        ROUND((C.POPULATION_15_19_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_15_19,
        ROUND((C.POPULATION_20_24_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_20_24,
        ROUND((C.POPULATION_25_34_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_25_34,
        ROUND((C.POPULATION_35_44_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_35_44,
        ROUND((C.POPULATION_45_54_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_45_54,
        ROUND((C.POPULATION_55_64_YEARS_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_55_64,
        ROUND(((C.POPULATION_65_74_YEARS_TOTAL + C.POPULATION_75_84_YEARS_TOTAL + 
                C.POPULATION_STATISTICS_AGED_85_AND_OVER_TOTAL)::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_AGE_65_PLUS,
        
        -- HOUSEHOLD CHARACTERISTICS
        C.AVERAGE_HOUSEHOLD_SIZE,
        C.AVERAGE_NUMBER_PERSONS_PER_BEDROOM,
        C.MEDIAN_MORTGAGE_REPAY_MONTHLY,
        C.MEDIAN_RENT_WEEKLY,
        C.MEDIAN_TOTAL_HOUSEHOLD_INCOME_WEEKLY,
        C.MEDIAN_TOTAL_PERSONAL_INCOME_WEEKLY,
        
        -- EDUCATION LEVELS (AS PERCENTAGES)
        ROUND((C.HIGH_SCHOOL_COMPLETION_YEAR_12_EQ_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_YEAR_12_COMPLETION,
        
        -- CULTURAL DIVERSITY
        ROUND((C.BIRTHPLACE_ELSEWHERE_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_BORN_OVERSEAS,
        ROUND((C.LANGUAGE_SPOKEN_AT_HOME_OTHER_LANGUAGES_TOTAL::DECIMAL / C.TOTAL_PERSONS_TOTAL) * 100, 2) AS PCT_NON_ENGLISH_HOME
        
    FROM SELECTED_LGAS SL
    LEFT JOIN GOLD.G_DIM_CENSUS C 
        ON SL.LGA_CODE = C.LGA_CODE_2016
)

SELECT 
    REVENUE_RANK,
    LISTING_NEIGHBOURHOOD,
    REVENUE_PER_ACTIVE_LISTING,
    TOTAL_POPULATION,
    MEDIAN_AGE_PERSONS,
    PCT_FEMALE,
    PCT_MALE,
    PCT_AGE_25_34 AS "YOUNG ADULTS (25-34) %",
    PCT_AGE_35_44 AS "MIDDLE AGE (35-44) %", 
    PCT_AGE_65_PLUS AS "SENIORS (65+) %",
    AVERAGE_HOUSEHOLD_SIZE,
    AVERAGE_NUMBER_PERSONS_PER_BEDROOM,
    MEDIAN_TOTAL_HOUSEHOLD_INCOME_WEEKLY,
    MEDIAN_MORTGAGE_REPAY_MONTHLY,
    MEDIAN_RENT_WEEKLY,
    PCT_YEAR_12_COMPLETION AS "YEAR 12 COMPLETION %",
    PCT_BORN_OVERSEAS AS "BORN OVERSEAS %",
    PCT_NON_ENGLISH_HOME AS "NON-ENGLISH HOME %"
FROM LGA_DEMOGRAPHICS

--QUESTION 4B
WITH 
LGA_REVENUE AS (
	SELECT
        G.LGA_CODE,
	    D.LISTING_NEIGHBOURHOOD,
	    AVG(D.AVG_ESTIMATED_REVENUE_PER_ACTIVE_LISTING) AS REVENUE_PER_ACTIVE_LISTING
	FROM GOLD.DM_LISTING_NEIGHBOURHOOD D
    JOIN GOLD.G_DIM_LGA_SUBURB G
    ON D.LISTING_NEIGHBOURHOOD = G.LGA_NAME
    GROUP BY G.LGA_CODE, D.LISTING_NEIGHBOURHOOD 
    ORDER BY 1, 2
)

-- CALCULATE CORRELATION COEFFICIENT OF MEDIAN AGE AND REVENUE PER ACTIVE LISTING 
SELECT 
    CORR(C.MEDIAN_AGE_PERSONS, L.REVENUE_PER_ACTIVE_LISTING) AS CORRELATION_COEFFICIENT
FROM LGA_REVENUE L 
JOIN C ON L.LGA_CODE = C.LGA_CODE_2016

--QUESTION 4C
WITH
PERF AS (
    SELECT 
    LISTING_NEIGHBOURHOOD,
    SUM(AVG_ESTIMATED_REVENUE_PER_ACTIVE_LISTING) AS TOTAL_REVENUE,
    SUM(TOTAL_STAYS) AS TOTAL_STAYS
    FROM GOLD.DM_LISTING_NEIGHBOURHOOD
    GROUP BY LISTING_NEIGHBOURHOOD
),

RANKED AS (
    SELECT
        LISTING_NEIGHBOURHOOD,
        TOTAL_REVENUE,
        TOTAL_STAYS,
        RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS REVENUE_RANK
    FROM PERF
),

TOP5_NEIGHBOURHOODS AS (
    SELECT *
    FROM RANKED
    WHERE REVENUE_RANK <= 5
),

PROPERTY_ANALYSIS AS (
    SELECT
        T.LISTING_NEIGHBOURHOOD,
        P.PROPERTY_TYPE,
        P.ROOM_TYPE,
        P.ACCOMMODATES,
        SUM(P.TOTAL_STAYS) AS TOTAL_STAYS,
        SUM(P.AVG_ESTIMATED_REVENUE_PER_ACTIVE_LISTING) AS REVENUE_PER_ACTIVE_LISTING
    FROM GOLD.DM_PROPERTY_TYPE P
    JOIN TOP5_NEIGHBOURHOODS T
      ON P.LISTING_NEIGHBOURHOOD = T.LISTING_NEIGHBOURHOOD
    GROUP BY
        T.LISTING_NEIGHBOURHOOD,
        P.PROPERTY_TYPE,
        P.ROOM_TYPE,
        P.ACCOMMODATES
)

SELECT *
FROM PROPERTY_ANALYSIS
ORDER BY LISTING_NEIGHBOURHOOD, REVENUE_PER_ACTIVE_LISTING DESC

--QUESTION 4D
WITH 
NEIGHBOURHOODS AS(
    SELECT 
    F.HOST_ID,
    G.LISTING_NEIGHBOURHOOD,
    G.LISTING_ID
    FROM GOLD.G_FACT F
    JOIN GOLD.G_DIM_PROPERTY G
    ON F.LISTING_ID = G.LISTING_ID
),
HOST_WIH_MUTIPLE_LISTINGS AS(
    SELECT 
    HOST_ID,
    COUNT(LISTING_ID)
    FROM NEIGHBOURHOODS
    GROUP BY HOST_ID
    HAVING COUNT(LISTING_ID) > 1
),
LGA_LISTING AS (
    SELECT 
    H.HOST_ID,
    COUNT(DISTINCT N.LISTING_NEIGHBOURHOOD) AS LGA_NUM
    FROM HOST_WIH_MUTIPLE_LISTINGS H
    JOIN NEIGHBOURHOODS N
    ON H.HOST_ID = N.HOST_ID
    GROUP BY H.HOST_ID
)
SELECT
CASE 
    WHEN  
        LGA_NUM = 1 THEN 'SAME LGA'
    WHEN 
        LGA_NUM > 1 THEN 'DIFFERENT LGA'
END AS LGA_DISTRIBUTION,
COUNT(*) AS NUM_HOSTS
FROM LGA_LISTING
GROUP BY LGA_DISTRIBUTION

--QUESTION 4E
WITH
REVENUE AS (
    SELECT
        LISTING_ID,
        ROUND(SUM(CASE WHEN HAS_AVAILABILITY = 1 THEN (30 - AVAILABILITY_30) * PRICE END), 2) AS ESTIMATED_MONTHLY_REVENUE
    FROM GOLD.G_FACT
    GROUP BY LISTING_ID
),

SINGLE_HOST_IDS AS (
    SELECT
        HOST_ID,
        COUNT(DISTINCT LISTING_ID) AS LISTING_COUNT
    FROM GOLD.G_FACT
    GROUP BY HOST_ID
    HAVING COUNT(DISTINCT LISTING_ID) = 1
),

LISTING_HOST AS (
    SELECT DISTINCT
        LISTING_ID,
        HOST_ID
    FROM GOLD.G_FACT
),

SINGLE_HOST_REVENUE AS (
    SELECT
        LH.HOST_ID,
        LH.LISTING_ID,
        R.ESTIMATED_MONTHLY_REVENUE,
        ROUND(R.ESTIMATED_MONTHLY_REVENUE * 12, 2) AS ESTIMATED_ANNUAL_REVENUE
    FROM LISTING_HOST LH
    JOIN REVENUE R USING (LISTING_ID)
    JOIN SINGLE_HOST_IDS S ON LH.HOST_ID = S.HOST_ID
),

LISTING_NEIGHBOURHOOD AS (
    SELECT DISTINCT
        P.LISTING_ID,
        P.LISTING_NEIGHBOURHOOD AS LISTING_NEIGHBOURHOOD
    FROM GOLD.G_DIM_PROPERTY P
),

SINGLE_REVENUE_LGA AS (
    SELECT
        SR.HOST_ID,
        SR.LISTING_ID,
        LN.LISTING_NEIGHBOURHOOD,
        SR.ESTIMATED_ANNUAL_REVENUE
    FROM SINGLE_HOST_REVENUE SR
    LEFT JOIN LISTING_NEIGHBOURHOOD LN ON SR.LISTING_ID = LN.LISTING_ID
),

MORTGAGE AS (
    SELECT
        L.LGA_CODE,
        TRIM(L.LGA_NAME) AS LGA_NAME,
        (C.MEDIAN_MORTGAGE_REPAY_MONTHLY * 12) AS ANNUAL_MORTGAGE
    FROM GOLD.G_DIM_CENSUS C
    JOIN GOLD.G_DIM_LGA_SUBURB L
      ON C.LGA_CODE_2016 = L.LGA_CODE
    WHERE C.MEDIAN_MORTGAGE_REPAY_MONTHLY IS NOT NULL
),

SINGLE_WITH_LGA AS (
    SELECT
        SRL.HOST_ID,
        SRL.LISTING_ID,
        SRL.ESTIMATED_ANNUAL_REVENUE,
        SRL.LISTING_NEIGHBOURHOOD,
        M.LGA_CODE,
        M.LGA_NAME,
        M.ANNUAL_MORTGAGE
    FROM SINGLE_REVENUE_LGA SRL
    LEFT JOIN MORTGAGE M
      ON SRL.LISTING_NEIGHBOURHOOD = M.LGA_NAME
),

COVERAGE AS (
SELECT
	COALESCE(SWL.LGA_CODE, 'UNMAPPED') AS LGA_CODE,
	COALESCE(SWL.LGA_NAME, 'UNMAPPED') AS LGA_NAME,
	COUNT(*) AS TOTAL_SINGLE_HOSTS,
	SUM(CASE WHEN SWL.ESTIMATED_ANNUAL_REVENUE >= SWL.ANNUAL_MORTGAGE THEN 1 ELSE 0 END) AS COVERED_HOSTS
FROM
	SINGLE_WITH_LGA SWL
GROUP BY
	1,
	2
)

SELECT
    LGA_CODE,
    LGA_NAME,
    TOTAL_SINGLE_HOSTS,
    COVERED_HOSTS,
    ROUND((COVERED_HOSTS::NUMERIC / NULLIF(TOTAL_SINGLE_HOSTS,0)) * 100, 2) AS PCT_COVERED
FROM COVERAGE
ORDER BY PCT_COVERED DESC, TOTAL_SINGLE_HOSTS DESC





