name: "bde_at3"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" 
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  bde_at3:
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      star:
        +materialized: table
        +schema: gold
      mart:
        +materialized: view
        +schema: gold
snapshots:
  bde_at3:
    +schema: silver